### ISSUE TITLE
android - cpp  视频无法播放

### ISSUE THREAD

**Issue by tinybearc** [sdkbox/sdkbox-sample-vungle#2]
###  vungle   版本：2.2.2.0

视频无法播放

~~~
05-18 21:54:24.402: D/cocos2d-x debug info(5959): sdkbox::PluginVungle::show("video")
05-18 21:54:26.054: W/VungleDevice(5959): no device ID available
05-18 21:54:26.055: E/VungleProtocol(5959): error requesting local ad
05-18 21:54:26.055: E/VungleProtocol(5959): com.vungle.publisher.el: timeout after 5000 ms
05-18 21:54:26.055: E/VungleProtocol(5959): 	at com.vungle.publisher.env.AndroidDevice.s(vungle:161)
05-18 21:54:26.055: E/VungleProtocol(5959): 	at com.vungle.publisher.env.AndroidDevice.a(vungle:72)
05-18 21:54:26.055: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.message.RequestAd$Factory.b(vungle:77)
05-18 21:54:26.055: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.message.RequestLocalAd$Factory.c(vungle:93)
05-18 21:54:26.055: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.RequestLocalAdHttpRequest$Factory.d(vungle:52)
05-18 21:54:26.055: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.RequestLocalAdHttpTransactionFactory.a(vungle:23)
05-18 21:54:26.055: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.ProtocolHttpGateway$3.run(vungle:137)
05-18 21:54:26.055: E/VungleProtocol(5959): 	at com.vungle.publisher.async.ScheduledPriorityExecutor$a$a.run(vungle:259)
05-18 21:54:26.055: E/VungleProtocol(5959): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-18 21:54:26.055: E/VungleProtocol(5959): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-18 21:54:26.055: E/VungleProtocol(5959): 	at java.lang.Thread.run(Thread.java:818)
05-18 21:54:29.417: W/VungleDevice(5959): no device ID available
05-18 21:54:29.418: E/VungleProtocol(5959): error sending unfilled ad
05-18 21:54:29.418: E/VungleProtocol(5959): com.vungle.publisher.el: timeout after 5000 ms
05-18 21:54:29.418: E/VungleProtocol(5959): 	at com.vungle.publisher.env.AndroidDevice.s(vungle:161)
05-18 21:54:29.418: E/VungleProtocol(5959): 	at com.vungle.publisher.env.AndroidDevice.a(vungle:72)
05-18 21:54:29.418: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.UnfilledAdHttpRequest$Factory.a(vungle:50)
05-18 21:54:29.418: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.UnfilledAdHttpTransactionFactory.a(vungle:23)
05-18 21:54:29.418: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.ProtocolHttpGateway$8.run(vungle:272)
05-18 21:54:29.418: E/VungleProtocol(5959): 	at com.vungle.publisher.async.ScheduledPriorityExecutor$a$a.run(vungle:259)
05-18 21:54:29.418: E/VungleProtocol(5959): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-18 21:54:29.418: E/VungleProtocol(5959): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-18 21:54:29.418: E/VungleProtocol(5959): 	at java.lang.Thread.run(Thread.java:818)
05-18 21:54:31.059: W/VungleDevice(5959): no device ID available
05-18 21:54:31.063: E/VungleProtocol(5959): error requesting local ad
05-18 21:54:31.063: E/VungleProtocol(5959): com.vungle.publisher.el: timeout after 5000 ms
05-18 21:54:31.063: E/VungleProtocol(5959): 	at com.vungle.publisher.env.AndroidDevice.s(vungle:161)
05-18 21:54:31.063: E/VungleProtocol(5959): 	at com.vungle.publisher.env.AndroidDevice.a(vungle:72)
05-18 21:54:31.063: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.message.RequestAd$Factory.b(vungle:77)
05-18 21:54:31.063: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.message.RequestLocalAd$Factory.c(vungle:93)
05-18 21:54:31.063: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.RequestLocalAdHttpRequest$Factory.d(vungle:52)
05-18 21:54:31.063: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.RequestLocalAdHttpTransactionFactory.a(vungle:23)
05-18 21:54:31.063: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.ProtocolHttpGateway$3.run(vungle:137)
05-18 21:54:31.063: E/VungleProtocol(5959): 	at com.vungle.publisher.async.ScheduledPriorityExecutor$a$a.run(vungle:259)
05-18 21:54:31.063: E/VungleProtocol(5959): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-18 21:54:31.063: E/VungleProtocol(5959): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-18 21:54:31.063: E/VungleProtocol(5959): 	at java.lang.Thread.run(Thread.java:818)
05-18 21:54:36.067: W/VungleDevice(5959): no device ID available
05-18 21:54:36.068: E/VungleProtocol(5959): error requesting local ad
05-18 21:54:36.068: E/VungleProtocol(5959): com.vungle.publisher.el: timeout after 5000 ms
05-18 21:54:36.068: E/VungleProtocol(5959): 	at com.vungle.publisher.env.AndroidDevice.s(vungle:161)
05-18 21:54:36.068: E/VungleProtocol(5959): 	at com.vungle.publisher.env.AndroidDevice.a(vungle:72)
05-18 21:54:36.068: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.message.RequestAd$Factory.b(vungle:77)
05-18 21:54:36.068: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.message.RequestLocalAd$Factory.c(vungle:93)
05-18 21:54:36.068: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.RequestLocalAdHttpRequest$Factory.d(vungle:52)
05-18 21:54:36.068: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.RequestLocalAdHttpTransactionFactory.a(vungle:23)
05-18 21:54:36.068: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.ProtocolHttpGateway$3.run(vungle:137)
05-18 21:54:36.068: E/VungleProtocol(5959): 	at com.vungle.publisher.async.ScheduledPriorityExecutor$a$a.run(vungle:259)
05-18 21:54:36.068: E/VungleProtocol(5959): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-18 21:54:36.068: E/VungleProtocol(5959): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-18 21:54:36.068: E/VungleProtocol(5959): 	at java.lang.Thread.run(Thread.java:818)
05-18 21:54:36.208: D/cocos2d-x debug info(5959): sdkbox::PluginVungle::show("reward")
05-18 21:54:41.070: W/VungleDevice(5959): no device ID available
05-18 21:54:41.074: E/VungleProtocol(5959): error requesting local ad
05-18 21:54:41.074: E/VungleProtocol(5959): com.vungle.publisher.el: timeout after 5000 ms
05-18 21:54:41.074: E/VungleProtocol(5959): 	at com.vungle.publisher.env.AndroidDevice.s(vungle:161)
05-18 21:54:41.074: E/VungleProtocol(5959): 	at com.vungle.publisher.env.AndroidDevice.a(vungle:72)
05-18 21:54:41.074: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.message.RequestAd$Factory.b(vungle:77)
05-18 21:54:41.074: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.message.RequestLocalAd$Factory.c(vungle:93)
05-18 21:54:41.074: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.RequestLocalAdHttpRequest$Factory.d(vungle:52)
05-18 21:54:41.074: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.RequestLocalAdHttpTransactionFactory.a(vungle:23)
05-18 21:54:41.074: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.ProtocolHttpGateway$3.run(vungle:137)
05-18 21:54:41.074: E/VungleProtocol(5959): 	at com.vungle.publisher.async.ScheduledPriorityExecutor$a$a.run(vungle:259)
05-18 21:54:41.074: E/VungleProtocol(5959): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-18 21:54:41.074: E/VungleProtocol(5959): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-18 21:54:41.074: E/VungleProtocol(5959): 	at java.lang.Thread.run(Thread.java:818)
05-18 21:54:41.225: W/VungleDevice(5959): no device ID available
05-18 21:54:41.227: E/VungleProtocol(5959): error sending unfilled ad
05-18 21:54:41.227: E/VungleProtocol(5959): com.vungle.publisher.el: timeout after 5000 ms
05-18 21:54:41.227: E/VungleProtocol(5959): 	at com.vungle.publisher.env.AndroidDevice.s(vungle:161)
05-18 21:54:41.227: E/VungleProtocol(5959): 	at com.vungle.publisher.env.AndroidDevice.a(vungle:72)
05-18 21:54:41.227: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.UnfilledAdHttpRequest$Factory.a(vungle:50)
05-18 21:54:41.227: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.UnfilledAdHttpTransactionFactory.a(vungle:23)
05-18 21:54:41.227: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.ProtocolHttpGateway$8.run(vungle:272)
05-18 21:54:41.227: E/VungleProtocol(5959): 	at com.vungle.publisher.async.ScheduledPriorityExecutor$a$a.run(vungle:259)
05-18 21:54:41.227: E/VungleProtocol(5959): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-18 21:54:41.227: E/VungleProtocol(5959): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-18 21:54:41.227: E/VungleProtocol(5959): 	at java.lang.Thread.run(Thread.java:818)
05-18 21:54:46.078: W/VungleDevice(5959): no device ID available
05-18 21:54:46.080: E/VungleProtocol(5959): error requesting local ad
05-18 21:54:46.080: E/VungleProtocol(5959): com.vungle.publisher.el: timeout after 5000 ms
05-18 21:54:46.080: E/VungleProtocol(5959): 	at com.vungle.publisher.env.AndroidDevice.s(vungle:161)
05-18 21:54:46.080: E/VungleProtocol(5959): 	at com.vungle.publisher.env.AndroidDevice.a(vungle:72)
05-18 21:54:46.080: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.message.RequestAd$Factory.b(vungle:77)
05-18 21:54:46.080: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.message.RequestLocalAd$Factory.c(vungle:93)
05-18 21:54:46.080: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.RequestLocalAdHttpRequest$Factory.d(vungle:52)
05-18 21:54:46.080: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.RequestLocalAdHttpTransactionFactory.a(vungle:23)
05-18 21:54:46.080: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.ProtocolHttpGateway$3.run(vungle:137)
05-18 21:54:46.080: E/VungleProtocol(5959): 	at com.vungle.publisher.async.ScheduledPriorityExecutor$a$a.run(vungle:259)
05-18 21:54:46.080: E/VungleProtocol(5959): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-18 21:54:46.080: E/VungleProtocol(5959): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-18 21:54:46.080: E/VungleProtocol(5959): 	at java.lang.Thread.run(Thread.java:818)
05-18 21:54:51.084: W/VungleDevice(5959): no device ID available
05-18 21:54:51.090: E/VungleProtocol(5959): error requesting local ad
05-18 21:54:51.090: E/VungleProtocol(5959): com.vungle.publisher.el: timeout after 5000 ms
05-18 21:54:51.090: E/VungleProtocol(5959): 	at com.vungle.publisher.env.AndroidDevice.s(vungle:161)
05-18 21:54:51.090: E/VungleProtocol(5959): 	at com.vungle.publisher.env.AndroidDevice.a(vungle:72)
05-18 21:54:51.090: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.message.RequestAd$Factory.b(vungle:77)
05-18 21:54:51.090: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.message.RequestLocalAd$Factory.c(vungle:93)
05-18 21:54:51.090: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.RequestLocalAdHttpRequest$Factory.d(vungle:52)
05-18 21:54:51.090: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.RequestLocalAdHttpTransactionFactory.a(vungle:23)
05-18 21:54:51.090: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.ProtocolHttpGateway$3.run(vungle:137)
05-18 21:54:51.090: E/VungleProtocol(5959): 	at com.vungle.publisher.async.ScheduledPriorityExecutor$a$a.run(vungle:259)
05-18 21:54:51.090: E/VungleProtocol(5959): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-18 21:54:51.090: E/VungleProtocol(5959): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-18 21:54:51.090: E/VungleProtocol(5959): 	at java.lang.Thread.run(Thread.java:818)
05-18 21:54:56.097: W/VungleDevice(5959): no device ID available
05-18 21:54:56.099: E/VungleProtocol(5959): error requesting local ad
05-18 21:54:56.099: E/VungleProtocol(5959): com.vungle.publisher.el: timeout after 5000 ms
05-18 21:54:56.099: E/VungleProtocol(5959): 	at com.vungle.publisher.env.AndroidDevice.s(vungle:161)
05-18 21:54:56.099: E/VungleProtocol(5959): 	at com.vungle.publisher.env.AndroidDevice.a(vungle:72)
05-18 21:54:56.099: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.message.RequestAd$Factory.b(vungle:77)
05-18 21:54:56.099: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.message.RequestLocalAd$Factory.c(vungle:93)
05-18 21:54:56.099: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.RequestLocalAdHttpRequest$Factory.d(vungle:52)
05-18 21:54:56.099: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.RequestLocalAdHttpTransactionFactory.a(vungle:23)
05-18 21:54:56.099: E/VungleProtocol(5959): 	at com.vungle.publisher.protocol.ProtocolHttpGateway$3.run(vungle:137)
05-18 21:54:56.099: E/VungleProtocol(5959): 	at com.vungle.publisher.async.ScheduledPriorityExecutor$a$a.run(vungle:259)
05-18 21:54:56.099: E/VungleProtocol(5959): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-18 21:54:56.099: E/VungleProtocol(5959): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-18 21:54:56.099: E/VungleProtocol(5959): 	at java.lang.Thread.run(Thread.java:818)

~~~

**Comment by yinjimmy** [comment]
works fine, 2.2.2.0 cpp version
