### ISSUE TITLE
cpp - android

### ISSUE THREAD

**Issue by tinybearc** [sdkbox/sdkbox-sample-vungle#7]
### vungle 版本：2.2.3.1 

按钮点击无效

log：
~~~
06-06 20:31:47.414: D/cocos2d-x debug info(17350): sdkbox::PluginVungle::show("video")
06-06 20:31:51.883: W/VungleDevice(17350): no device ID available
06-06 20:31:51.886: E/VungleProtocol(17350): error requesting local ad
06-06 20:31:51.886: E/VungleProtocol(17350): com.vungle.publisher.el: timeout after 5000 ms
06-06 20:31:51.886: E/VungleProtocol(17350): 	at com.vungle.publisher.env.AndroidDevice.s(vungle:161)
06-06 20:31:51.886: E/VungleProtocol(17350): 	at com.vungle.publisher.env.AndroidDevice.a(vungle:72)
06-06 20:31:51.886: E/VungleProtocol(17350): 	at com.vungle.publisher.protocol.message.RequestAd$Factory.b(vungle:77)
06-06 20:31:51.886: E/VungleProtocol(17350): 	at com.vungle.publisher.protocol.message.RequestLocalAd$Factory.c(vungle:93)
06-06 20:31:51.886: E/VungleProtocol(17350): 	at com.vungle.publisher.protocol.RequestLocalAdHttpRequest$Factory.d(vungle:52)
06-06 20:31:51.886: E/VungleProtocol(17350): 	at com.vungle.publisher.protocol.RequestLocalAdHttpTransactionFactory.a(vungle:23)
06-06 20:31:51.886: E/VungleProtocol(17350): 	at com.vungle.publisher.protocol.ProtocolHttpGateway$3.run(vungle:137)
06-06 20:31:51.886: E/VungleProtocol(17350): 	at com.vungle.publisher.async.ScheduledPriorityExecutor$a$a.run(vungle:259)
06-06 20:31:51.886: E/VungleProtocol(17350): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-06 20:31:51.886: E/VungleProtocol(17350): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-06 20:31:51.886: E/VungleProtocol(17350): 	at java.lang.Thread.run(Thread.java:818)


06-06 20:33:45.048: D/cocos2d-x debug info(17350): sdkbox::PluginVungle::show("reward")
06-06 20:33:47.061: W/VungleDevice(17350): no device ID available
06-06 20:33:47.065: E/VungleProtocol(17350): error requesting local ad
06-06 20:33:47.065: E/VungleProtocol(17350): com.vungle.publisher.el: timeout after 5000 ms
06-06 20:33:47.065: E/VungleProtocol(17350): 	at com.vungle.publisher.env.AndroidDevice.s(vungle:161)
06-06 20:33:47.065: E/VungleProtocol(17350): 	at com.vungle.publisher.env.AndroidDevice.a(vungle:72)
06-06 20:33:47.065: E/VungleProtocol(17350): 	at com.vungle.publisher.protocol.message.RequestAd$Factory.b(vungle:77)
06-06 20:33:47.065: E/VungleProtocol(17350): 	at com.vungle.publisher.protocol.message.RequestLocalAd$Factory.c(vungle:93)
06-06 20:33:47.065: E/VungleProtocol(17350): 	at com.vungle.publisher.protocol.RequestLocalAdHttpRequest$Factory.d(vungle:52)
06-06 20:33:47.065: E/VungleProtocol(17350): 	at com.vungle.publisher.protocol.RequestLocalAdHttpTransactionFactory.a(vungle:23)
06-06 20:33:47.065: E/VungleProtocol(17350): 	at com.vungle.publisher.protocol.ProtocolHttpGateway$3.run(vungle:137)
06-06 20:33:47.065: E/VungleProtocol(17350): 	at com.vungle.publisher.async.ScheduledPriorityExecutor$a$a.run(vungle:259)
06-06 20:33:47.065: E/VungleProtocol(17350): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-06 20:33:47.065: E/VungleProtocol(17350): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-06 20:33:47.065: E/VungleProtocol(17350): 	at java.lang.Thread.run(Thread.java:818)

~~~

**Comment by yinjimmy** [comment]
网络超时

com.vungle.publisher.el: timeout after 5000 ms

**Comment by yinjimmy** [comment]
确定代理是否工作。。
